<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <AssemblyName>SupportTools.KurrentDbClient</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="KurrentDB.Client" Version="1.4.1" />
  </ItemGroup>
</Project>
