name: Nightly PowerShell Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  pester-tests:
    name: Run PowerShell Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Ensure Pester is Available
        shell: pwsh
        run: |
          if (-not (Get-Module -ListAvailable -Name Pester)) {
            Install-Module -Name Pester -Force -SkipPublisherCheck -Scope CurrentUser
          }

      - name: Run Pester Tests
        shell: pwsh
        run: |
          Invoke-Pester -Path ./Scripts/Tests -CI
